services:
  home:
      build: ./home
      ports:
        - "8080:80"

  mysql_clientes:
    image: mysql:8.0
    container_name: mysql_clientes
    environment:
      MYSQL_ROOT_PASSWORD: ${CLIENTES_DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${CLIENTES_DB_NAME}
      MYSQL_USER: ${CLIENTES_DB_USER}
      MYSQL_PASSWORD: ${CLIENTES_DB_PASSWORD}
    ports:
      - "${CLIENTES_MYSQL_HOST_PORT}:3306"
    volumes:
      - clientes_data:/var/lib/mysql

  clientes:
    build: ./clientes
    container_name: servicio_clientes
    env_file:
      - ./clientes/.env
    ports:
      - "${CLIENTES_PORT}:${CLIENTES_PORT}"
    depends_on:
      - mysql_clientes

  mysql_asesores:
    image: mysql:8.0
    container_name: mysql_asesores
    environment:
      MYSQL_ROOT_PASSWORD: ${ASESORES_DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${ASESORES_DB_NAME}
      MYSQL_USER: ${ASESORES_DB_USER}
      MYSQL_PASSWORD: ${ASESORES_DB_PASSWORD}
    ports:
      - "${ASESORES_MYSQL_HOST_PORT}:3306"
    volumes:
      - asesores_data:/var/lib/mysql

  asesores:
    build: ./asesores
    container_name: servicio_asesores
    env_file:
      - ./asesores/.env
    ports:
      - "${ASESORES_PORT}:${ASESORES_PORT}"
    depends_on:
      - mysql_asesores

  mysql_turnos:
    image: mysql:8.0
    container_name: mysql_turnos
    environment:
      MYSQL_ROOT_PASSWORD: ${TURNOS_DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${TURNOS_DB_NAME}
      MYSQL_USER: ${TURNOS_DB_USER}
      MYSQL_PASSWORD: ${TURNOS_DB_PASSWORD}
    ports:
      - "${TURNOS_MYSQL_HOST_PORT}:3306"
    volumes:
      - turnos_data:/var/lib/mysql

  turnos:
    build: ./turnos
    container_name: servicio_turnos
    env_file:
      - ./turnos/.env
    ports:
      - "${TURNOS_PORT}:${TURNOS_PORT}"
    depends_on:
      - mysql_turnos

volumes:
  clientes_data:
  asesores_data:
  turnos_data:
